### ISSUE TITLE
[carefreelife98] 24.03.17 yolo model test: 정상 동작 확인, Iphone Cam 을 활용한 객체 탐지 성공

### ISSUE THREAD

**Issue by carefreelife98** [CapstoneDesignCSE/capstone_design2#3]
# 24.03.17 진행 사항
- @SGT-Cho 님이 학습시켜놓은 Yolo Model 로컬 테스트 진행 및 동작 확인
- [개발 환경 세팅] Git Branch 생성, Pycharm Init
- 맥과 아이폰 연속성으로 YoloV8 실시간 객체 탐지 (차량, 사람) 성공
[아이폰 캠 활용 YoloV8 테스트](https://inu-capstone-design2.s3.ap-northeast-2.amazonaws.com/YoloV8_Iphone_%E1%84%8B%E1%85%A7%E1%86%AB%E1%84%83%E1%85%A9%E1%86%BC%E1%84%89%E1%85%A5%E1%86%BC%E1%84%80%E1%85%A9%E1%86%BC.mov)

# TODO
- 소형, 중형 승용차 정상 식별되나 대형 및 버스 등의 차량 식별 기능 미비.
- 대형 차량 학습 데이터 요구됨.

**Comment by SGT-Cho** [comment]
# TODO
- 샘플 영상 기반으로 차량 속도 측정 
- 인도(sidewalk) 쪽 객체 탐지 필요
